{% set name = "ncempy" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed80f99acf5e31981e514c0d18afcb2ca67aa048827a48c6922faae7af303b37

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - ncem2png = ncempy.command_line.ncem2png:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy
    - scipy
    - matplotlib-base
    - h5py
    - setuptools

test:
  imports:
    - ncempy
  commands:
    - ncem2png --help

about:
  home: https://github.com/ercius/openNCEM
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A collection of packages and tools for electron microscopy data analysis supported by the National Center for Electron Microscopy facility of the Molecular Foundry
  doc_url: https://openncem.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tschoonj
